/// Generalized types supported by DataJoint.
#[repr(i32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, FromPrimitive)]
pub enum DataJointType {
    Unknown,
    Boolean,
    TinyInt,
    TinyIntUnsigned,
    SmallInt,
    SmallIntUnsigned,
    MediumInt,
    MediumIntUnsigned,
    Int,
    IntUnsigned,
    BigInt,
    BigIntUnsigned,
    Enum,
    Date,
    Time,
    DateTime,
    Timestamp,
    CharN,
    VarCharN,
    Float,
    Double,
    Decimal,
    TinyBlob,
    MediumBlob,
    Blob,
    LongBlob,
    Attach,
    FilepathStore,
}
